### ISSUE TITLE
[FEATURE] Onboarding Animation 구현

### ISSUE THREAD

**Issue by uxri** [TeamDearToday/Deartoday-Android#24]
## 📝  To-do
- [ ] TextView Animation 적용
- [ ] Button Animation 적용
- [ ] Letter Animation 적용

## 📆 Date
0710 - 0712
