### ISSUE TITLE
[CHORE] Onboarding Animation 코드 수정

### ISSUE THREAD

**Issue by uxri** [TeamDearToday/Deartoday-Android#28]
## 📝  To-do

- [ ] XML 파일 수정
- [ ] Animation delay, duration 수정
- [ ] 로티 적용
- [ ] 온보딩 백버튼 막기

## 📆 Date
0711 - 0713
